# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy container app to Azure Web App - fastapi-cd-itcs-test

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: 'ubuntu-latest'

#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Log in to registry
#       uses: docker/login-action@v1
#       with:
#         registry: https://fastapicditcs.azurecr.io/
#         username: ${{ secrets.AzureAppService_ContainerUsername_ca3912b067c84c3bb4b6f7718c33e765 }}
#         password: ${{ secrets.AzureAppService_ContainerPassword_0a7802cb544b4dc59cb1282b853acc20 }}

#     - name: Build and push container image to registry
#       uses: docker/build-push-action@v2
#       with:
#         push: true
#         tags: fastapicditcs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca3912b067c84c3bb4b6f7718c33e765 }}/fastapi-cd:${{ github.sha }}
#         file: ./Dockerfile

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Deploy to Azure Web App
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: 'fastapi-cd-itcs-test'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AzureAppService_PublishProfile_96aa6551c17d482eb1e35f7e6144d1e9 }}
#         images: 'fastapicditcs.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ca3912b067c84c3bb4b6f7718c33e765 }}/fastapi-cd:${{ github.sha }}'
